=== CIRDLES/Squid/squidCore/src/test/resources/org/cirdles/squid/squidReports/squidReportTables/SquidReportTable.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="SquidReportTable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="reportTableName" type="xs:string"/>
        <xs:element name="reportCategories" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SquidReportCategory" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="displayName" type="xs:string"/>
                    <xs:element name="categoryColumns" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="SquidReportColumn" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="expressionName" type="xs:string"/>
                                <xs:element name="units" type="xs:string" minOccurs="0"/>
                                <xs:element name="uncertaintyColumn" minOccurs="0"/>
                                <xs:element name="amUncertaintyColumn" type="xs:boolean"/>
                                <xs:element name="uncertaintyDirective" type="xs:string" minOccurs="0"/>
                                <xs:element name="countOfSignificantDigits" type="xs:int"/>
                                <xs:element name="visible" type="xs:boolean"/>
                                <xs:element name="footnoteSpec" type="xs:string" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="visible" type="xs:boolean"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="reportSpotTarget" type="spotTypes" minOccurs="0"/>
        <xs:element name="isDefault" type="xs:boolean"/>
        <xs:element name="version" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="spotTypes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REFERENCE_MATERIAL"/>
      <xs:enumeration value="UNKNOWN"/>
      <xs:enumeration value="NONE"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== CIRDLES/Squid/squidCore/src/test/resources/org/cirdles/squid/squidReports/squidReportTables/Example.xml
<?xml version="1.0"?>
<!-- SQUIDREPORTTABLE_DATA_FILE -->
<SquidReportTable xmlns="https://raw.githubusercontent.com"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://raw.githubusercontent.com
                                ../schema/SquidReportTable.xsd">
  <reportTableName>Example</reportTableName>
  <reportCategories>
    <reportCategory>
      <displayName>Default Category</displayName>
      <categoryColumns>
        <SquidReportColumn>
          <expressionName>4cor_206Pb238U_Age</expressionName>
          <units></units>
          <uncertaintyColumn></uncertaintyColumn>
          <amUncertaintyColumn>false</amUncertaintyColumn>
          <uncertaintyDirective></uncertaintyDirective>
          <countOfSignificantDigits>0</countOfSignificantDigits>
          <visible>false</visible>
          <footnoteSpec></footnoteSpec>
        </SquidReportColumn>
      </categoryColumns>
      <visible>true</visible>
    </reportCategory>
  </reportCategories>
  <reportSpotTarget>UNKNOWN</reportSpotTarget>
  <isDefault>false</isDefault>
  <version>0</version>
</SquidReportTable>
