=== CIRDLES/Squid/squidCore/src/main/resources/org/cirdles/squid/schema/SquidTask_XMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://raw.githubusercontent.com" xmlns="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Task">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string" />
        <xs:element name="taskType" type="xs:string" />
        <xs:element name="description" type="xs:string" />
        <xs:element name="authorName" type="xs:string"/>
        <xs:element name="labName" type="xs:string" />
        <xs:element name="provenance" type="xs:string" />
        <xs:element name="dateRevised" type="xs:unsignedByte" />
        <xs:element name="parentNuclide" type="xs:unsignedByte" />
        <xs:element name="directAltPD" type="xs:boolean" />
        <xs:element name="nominalMasses">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="string" type="xs:decimal" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="indexOfBackgroundSpecies" type="xs:unsignedByte" />
        <xs:element name="ratioNames">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="string" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="specialSquidFourExpressionsMap">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="entry">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="string" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="customExpressions">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="ExpressionSpec">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="expressionName" type="xs:string" />
                    <xs:element name="excelExpressionString" type="xs:string" />
                    <xs:element name="squidSwitchNU" type="xs:boolean" />
                    <xs:element name="squidSwitchSCSummaryCalculation" type="xs:boolean" />
                    <xs:element name="squidSwitchSTReferenceMaterialCalculation" type="xs:boolean" />
                    <xs:element name="squidSwitchSAUnknownCalculation" type="xs:boolean" />
                    <xs:element name="squidSpecialUPbThExpression" type="xs:boolean" />
                    <xs:element name="squidSwitchConcentrationReferenceMaterialCalculation" type="xs:boolean" />
                    <xs:element name="notes" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CIRDLES/Squid/squidCore/src/test/resources/org/cirdles/squid/tasks/Z6266_=_11pk_Perm1.xml
<?xml version="1.0"?>
<!-- SQUID3_TASK_SPECIFICATION_FILE -->
<Task xmlns="https://raw.githubusercontent.com"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://raw.githubusercontent.com
                          ../schema/SquidTask_XMLSchema.xsd">
  <name>Z6266_=_11pk_Perm1</name>
  <taskType>GEOCHRON</taskType>
  <description>11-peak zircon (189-254), primary 206/238, secondary (208/232) calibrated indirectly, via 232Th/238U</description>
  <authorName></authorName>
  <labName>SB</labName>
  <provenance>SquidTask_Z6266 = 11pk Perm1.SB.xls</provenance>
  <dateRevised>0</dateRevised>
  <parentNuclide>238</parentNuclide>
  <directAltPD>false</directAltPD>
  <nominalMasses>
    <string>190</string>
    <string>195.8</string>
    <string>195.9</string>
    <string>204</string>
    <string>204.1</string>
    <string>206</string>
    <string>207</string>
    <string>208</string>
    <string>238</string>
    <string>248</string>
    <string>254</string>
  </nominalMasses>
  <indexOfBackgroundSpecies>4</indexOfBackgroundSpecies>
  <ratioNames>
    <string>190/195.8</string>
    <string>195.9/195.8</string>
    <string>204/206</string>
    <string>206/238</string>
    <string>206/254</string>
    <string>207/206</string>
    <string>208/206</string>
    <string>208/248</string>
    <string>238/195.8</string>
    <string>248/195.8</string>
    <string>248/254</string>
    <string>254/238</string>
  </ratioNames>
  <specialSquidFourExpressionsMap>
    <entry>
      <string>232Th238U_DEFAULT</string>
      <string>(0.03446*[&quot;254/238&quot;]+0.868)*[&quot;248/254&quot;]</string>
    </entry>
    <entry>
      <string>ParentElement_ConcenConst</string>
      <string>[&quot;238/195.8&quot;]/[&quot;254/238&quot;]^0.66</string>
    </entry>
    <entry>
      <string>Uncor_206Pb238U_CalibConst</string>
      <string>[&quot;206/238&quot;]/[&quot;254/238&quot;]^Expo_Used</string>
    </entry>
    <entry>
      <string>Uncor_208Pb232Th_CalibConst</string>
      <string>[&quot;208/248&quot;]</string>
    </entry>
  </specialSquidFourExpressionsMap>
  <customExpressions>
    <ExpressionSpec>
      <expressionName>Expo_Used</expressionName>
      <excelExpressionString>1.8</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>LnUOU</expressionName>
      <excelExpressionString>ln([&quot;254/238&quot;])</excelExpressionString>
      <squidSwitchNU>true</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>false</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>LnPbU</expressionName>
      <excelExpressionString>Ln([&quot;206/238&quot;])</excelExpressionString>
      <squidSwitchNU>true</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>false</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>lnUOU-sample</expressionName>
      <excelExpressionString>ln([&quot;254/238&quot;])</excelExpressionString>
      <squidSwitchNU>true</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>false</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>false</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>true</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>lnPbU-sample</expressionName>
      <excelExpressionString>Ln([&quot;206/238&quot;])</excelExpressionString>
      <squidSwitchNU>true</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>false</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>false</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>true</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Expo</expressionName>
      <excelExpressionString>RobReg(LnUOU,LnPbU)</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Yb_bwt</expressionName>
      <excelExpressionString>Biweight([&quot;190/195.8&quot;],9)</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Ybsen</expressionName>
      <excelExpressionString>69.85/Yb_bwt</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Ybsens1sigabserror</expressionName>
      <excelExpressionString>Yb_bwt21/Yb_bwt*Ybsen</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Hf_bwt</expressionName>
      <excelExpressionString>Biweight([&quot;195.9/195.8&quot;],9)</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
      <squidSwitchSAUnknownCalculation>false</squidSwitchSAUnknownCalculation>
      <squidSpecialUPbThExpression>false</squidSpecialUPbThExpression>
      <squidSwitchConcentrationReferenceMaterialCalculation>false</squidSwitchConcentrationReferenceMaterialCalculation>
      <notes>Custom expression imported from Squid2 task Z6266 = 11pk Perm1 .</notes>
    </ExpressionSpec>
    <ExpressionSpec>
      <expressionName>Hfsens</expressionName>
      <excelExpressionString>8200/Hf_bwt</excelExpressionString>
      <squidSwitchNU>false</squidSwitchNU>
      <squidSwitchSCSummaryCalculation>true</squidSwitchSCSummaryCalculation>
      <squidSwitchSTReferenceMaterialCalculation>true</squidSwitchSTReferenceMaterialCalculation>
